#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=31gb
#PBS -l walltime=10:00:00
#PBS -N networkneuro

set -e
set -x

export fsdir=`jq -r '.fsdir' config.json`

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 mri_convert $fsdir/mri/aparc+aseg.mgz --out_orientation RAS aparc+aseg.nii.gz

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

echo "Network Pipeline Complete"

if [ ! -s output/pconn.mat ];
then
    echo "output missing"
    exit 1
fi

echo "Generating surfaces/ vtk from aparc+aseg.mgz"
time singularity exec -e docker://brainlife/pythonvtk:1.1 ./freesurfer2vtks.py 

