#!/bin/bash
#PBS -l nodes=1:ppn=8:vmem=32gb
#PBS -l walltime=10:00:00
#PBS -N networkneuro

set -e
set -x

export fsdir=`jq -r '.fsdir' config.json`

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;

time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && mri_convert $fsdir/mri/aparc+aseg.mgz --out_orientation RAS aparc+aseg.nii.gz"

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

echo "Network Pipeline Complete"

if [ ! -s output/pconn.mat ];
then
    echo "output missing"
    exit 1
fi

#genearte vtk surfaces for each labels
time singularity exec -e docker://brainlife/docker-pythonvtk ./freesurfer2vtks.py 

#vtk should have decimate method that I can use in freesurfer2vtk 
#time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./decimate_surface.sh"

